title: Computational imaging
theme: jekyll-theme-cayman
github:
  home: https://captvansciencypants.github.io/computational-imaging-lab/
  research: https://captvansciencypants.github.io/computational-imaging-lab/research.html
  people: https://captvansciencypants.github.io/computational-imaging-lab/people.html
  publications: https://captvansciencypants.github.io/computational-imaging-lab/publications.html
  software: https://captvansciencypants.github.io/computational-imaging-lab/software.html
  teaching: https://captvansciencypants.github.io/computational-imaging-lab/teaching.html
