title: Computational imaging
theme: jekyll-theme-cayman
github:
  home: https://captvansciencypants.github.io/
  research: https://captvansciencypants.github.io/research.html
  people: https://captvansciencypants.github.io/people.html
  publications: https://captvansciencypants.github.io/publications.html
  software: https://captvansciencypants.github.io/software.html
  teaching: https://captvansciencypants.github.io/teaching.html
